global:
  scrape_interval: 2s
  scrape_timeout: 2s

scrape_configs:
  - job_name: 'db-load-test'
    static_configs:
      - targets: ['localhost:9100']  # Script exports metrics here
        labels:
          instance: 'db-load-test'

